apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    project: nginx-{{ .Values.namespace }}
  ports:
    - port: {{ .Values.service.clusterip.port }}
      targetPort: {{ .Values.service.clusterip.targetPort }}
