apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: nginx-{{ .Values.namespace }}
  template:
    metadata:
      labels:
        project: nginx-{{ .Values.namespace }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: config-vol
          configMap:
            name: {{ .Values.configmap.name }}
