apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: nginx-{{ .Values.namespace }}
  template:
    metadata:
      labels:
        project: nginx-{{ .Values.namespace }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-vol
              mountPath: /etc/config
      volumes:
        - name: config-vol
          configMap:
            name: {{ .Values.configmap.name }}
