apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    project: nginx-{{ .Values.namespace }}
  ports:
    - port: {{ .Values.service.nodeport.port }}
      targetPort: {{ .Values.service.nodeport.targetPort }}
      nodePort: {{ .Values.service.nodeport.nodePort }}
