# Staging environment overrides
replicaCount: 2
namespace: staging
image:
  repository: mithunkumarb2026/tap-app
  tag: ecedbe29c6a9a08560f836d5ad32d8f32fc0e5c4
configmap:
  name: mithun-staging
service:
  clusterip:
    port: 80
    targetPort: 80
  nodeport:
    port: 80
    targetPort: 80
    nodePort: 30003
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
