# Dev environment overrides
replicaCount: 1

namespace: dev

image:
  repository: BMithunKumar/tap-app    
  tag: abc123sha                   

configmap:
  name: mithun-dev

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi