# Staging environment overrides
replicaCount: 2
namespace: staging
image:
  repository: mithunkumarb2026/tap-app
  tag: e8877ed8197accc4b2b9673ab07e90c8a8472c2e
configmap:
  name: mithun-staging
service:
  clusterip:
    port: 80
    targetPort: 80
  nodeport:
    port: 80
    targetPort: 80
    nodePort: 30003
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
