# Dev environment overrides
replicaCount: 1
namespace: dev
image:
  repository: mithunkumarb2026/tap-app
  tag: ecedbe29c6a9a08560f836d5ad32d8f32fc0e5c4
configmap:
  name: mithun-dev
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
