# Default values for tap-app-app
replicaCount: 1

image:
  repository: tap-app
  tag: alpine
  pullPolicy: IfNotPresent

namespace: default

configmap:
  name: mithun

service:
  clusterip:
    port: 80
    targetPort: 80
  nodeport:
    port: 80
    targetPort: 80
    nodePort: 30002


resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi