apiVersion: v1
kind: Service
metadata:
  name: mysql-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql-{{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: mysql-{{ .Values.namespace }}
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
