apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace }}-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.cpu.requests | quote }}
    requests.memory: {{ .Values.quota.memory.requests }}
    limits.cpu: {{ .Values.quota.cpu.limits | quote }}
    limits.memory: {{ .Values.quota.memory.limits }}
    pods: {{ .Values.quota.pods | quote }}
    services: {{ .Values.quota.services | quote }}
    persistentvolumeclaims: {{ .Values.quota.pvcs | quote }}
    configmaps: {{ .Values.quota.configmaps | quote }}
    secrets: {{ .Values.quota.secrets | quote }}
