apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_PASSWORD: UzNjdXIzUEBzcyE=
  DB_ROOT_PASSWORD: cm9vdFBAc3N3b3Jk
  DB_USERNAME: YXBwdXNlcg==
