apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tap-app-staging
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/BMithunKumar/argocd-kubernetes.git
    targetRevision: HEAD
    path: helm/tap-app-app
    helm:
      valueFiles:
        - values.yaml
        - values.staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
