# Default values for nginx-app
replicaCount: 1

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

namespace: default

configmap:
  name: mithun

service:
  clusterip:
    port: 80
    targetPort: 80


resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi