# Staging environment overrides
replicaCount: 5

namespace: staging

image:
  repository: nginx
  tag: latest

configmap:
  name: mithun-staging

esources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi