# Staging environment overrides
replicaCount: 2

namespace: staging

image:
  repository: nginx
  tag: latest

configmap:
  name: mithun-staging

service:
  clusterip:
    port: 80
    targetPort: 80
  nodeport:
    port: 80
    targetPort: 80
    nodePort: 30003

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi