# Staging environment overrides
replicaCount: 3

namespace: staging

image:
  repository: nginx
  tag: latest

configmap:
  name: mithun-staging

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi